version: '3.0'

services:
  postgres:
    container_name: postgres_container
    image: postgres:15.0
    env_file:
      - ./config/.env.dev
    volumes:
       - ./database:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped